language: bash

env:
  global:
  - PROJECT_NAME=diesel-cli
  - IMAGE_NAME=${DOCKER_USERNAME}/${PROJECT_NAME}
  - DOCKERFILE_DIR=.
  - DOCKER_BUILD_TARGET=provider

matrix:
  include:
  - services: docker

before_script:
- set -e
- docker --version
# always test login
- docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"

script:
- |-
  export DIESEL_TAG=`
    curl https://raw.githubusercontent.com/diesel-rs/diesel/master/diesel_cli/Cargo.toml |
    grep -E "^version" |
    sed -E 's/version = "([[:digit:]].[[:digit:]].[[:digit:]])"/\1/'`
- echo ${DIESEL_TAG}
- export DIESEL_VER=`echo ${DIESEL_TAG} | grep -oP '(?<=v)\d+\.\d+\.\d+'`
- echo ${DIESEL_VER}
- |-
  docker build \
    --target ${DOCKER_BUILD_TARGET} \
    --build-arg DIESEL_VER=${DIESEL_VER} \
    -t ${IMAGE_NAME}:${DIESEL_TAG} \
    ${DOCKERFILE_DIR}

after_success:
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    docker push ${IMAGE_NAME}:${DIESEL_TAG}
    docker tag ${IMAGE_NAME}:${DIESEL_TAG} ${IMAGE_NAME}:latest
    docker push ${IMAGE_NAME}:latest
  fi

branches:
  only:
  - master
